# Confirm the package loads from source and pure functions behave.
suppressMessages(pkgload::load_all("C:/GitHub/HLAtools_fast", quiet = TRUE))
cat("load_all OK\n")
cat("HLAgazetteer$version:", HLAgazetteer$version, "\n")
cat("alleleListHistory version:", unlist(alleleListHistory$Version), "\n")
cat("nuc loci (", length(HLAgazetteer$nuc), "):", paste(HLAgazetteer$nuc, collapse=" "), "\n")
cat("gen loci (", length(HLAgazetteer$gen), "):", paste(HLAgazetteer$gen, collapse=" "), "\n")
cat("prot loci(", length(HLAgazetteer$prot), "):", paste(HLAgazetteer$prot, collapse=" "), "\n")
cat("--- sanity: pure fns ---\n")
cat('alleleTrim("A*03:01:01",2)        =', alleleTrim("A*03:01:01", 2), "\n")
cat('getField("HLA-A*01:01:01:01",3)   =', getField("HLA-A*01:01:01:01", 3), "\n")
cat('squashVersion("3.45.0")           =', squashVersion("3.45.0"), "\n")
cat('repoVersion("3.05.0")             =', repoVersion("3.05.0"), "\n")
cat('numFields("HLA-A*01:01")          =', numFields("HLA-A*01:01"), "\n")
